name = "portal-api"
main = "src/workers/proxy.js"
compatibility_date = "2025-01-01"
account_id = "e2d6828ee7890229a51772bae6c27aae"

[vars]
API_KEY = "mc-portal-3.0_8a2d7f9e4c1b5a6c3d2e1f0b9a8c7d6e"

[[routes]]
pattern = "portalapi.medicert.com.tr"
custom_domain = true

[[kv_namespaces]]
binding = "DB"
id = "8eb0dc6ffe2947729b29f0db1c84fd52"

[[d1_databases]]
binding = "DB_D1"
database_name = "medicert-portal"
database_id = "94b188bb-1ea8-4b84-ba00-8f7bf91bb265"
migrations_dir = "src/workers/migrations"
